apiVersion: v1
description: OpenStack-Helm libvirt
home: https://libvirt.org
maintainers:
- name: OpenStack-Helm Authors
name: libvirt
sources:
- https://libvirt.org/git/?p=libvirt.git;a=summary
- https://opendev.org/openstack/openstack-helm
version: 0.1.0
